import { defineType, defineField, defineArrayMember } from 'sanity'

export const page = defineType({
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL path)',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      description: 'The URL path without leading slash. Use "home" for the homepage; rendered at /.',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'sections',
      title: 'Sections',
      type: 'array',
      of: [
        defineArrayMember({ type: 'heroSection' }),
        defineArrayMember({ type: 'richTextSection' }),
        defineArrayMember({ type: 'ctaSection' }),
        defineArrayMember({ type: 'featureGridSection' }),
        defineArrayMember({ type: 'faqSection' }),
        defineArrayMember({ type: 'imageWithTextSection' }),
        defineArrayMember({ type: 'legalHeader' }),
        defineArrayMember({ type: 'legalProse' }),
        defineArrayMember({ type: 'legalContent' }),
        defineArrayMember({ type: 'proseSection' }),
        defineArrayMember({ type: 'iconHeading' }),
        defineArrayMember({ type: 'alertCallout' }),
        defineArrayMember({ type: 'infoCard' }),
        defineArrayMember({ type: 'buttonRow' }),
        defineArrayMember({ type: 'contactCallout' }),
        defineArrayMember({ type: 'pageFooterNote' }),
        defineArrayMember({ type: 'checklistCardGrid' }),
        defineArrayMember({ type: 'titledBulletCards' }),
        defineArrayMember({ type: 'iconBadgeCards' }),
        defineArrayMember({ type: 'checkmarkGrid' }),
        defineArrayMember({ type: 'accentNotes' }),
        defineArrayMember({ type: 'twoTierCards' }),
        defineArrayMember({ type: 'contentSection' }),
        defineArrayMember({ type: 'marketingHero' }),
        defineArrayMember({ type: 'statsBand' }),
        defineArrayMember({ type: 'storySection' }),
        defineArrayMember({ type: 'valueCardsGrid' }),
        defineArrayMember({ type: 'teamSection' }),
        defineArrayMember({ type: 'missionStatement' }),
        defineArrayMember({ type: 'awardsGrid' }),
        defineArrayMember({ type: 'marketingCtaBand' }),
        defineArrayMember({ type: 'centeredHeroBand' }),
        defineArrayMember({ type: 'tableOfContents' }),
        defineArrayMember({ type: 'definitionWithImage' }),
        defineArrayMember({ type: 'processCardsWithFormula' }),
        defineArrayMember({ type: 'borderAccentCards' }),
        defineArrayMember({ type: 'dosAndDontsColumns' }),
        defineArrayMember({ type: 'requirementCards' }),
        defineArrayMember({ type: 'faqAccordion' }),
        defineArrayMember({ type: 'gradientCtaBand' }),
        defineArrayMember({ type: 'imageHero' }),
        defineArrayMember({ type: 'splitContentChecklist' }),
        defineArrayMember({ type: 'numberedProcessCards' }),
        defineArrayMember({ type: 'iconFeatureGrid' }),
        defineArrayMember({ type: 'benefitsWithImage' }),
        defineArrayMember({ type: 'formCtaBand' }),
        defineArrayMember({ type: 'componentEmbed' }),
        defineArrayMember({ type: 'preQualIntro' }),
        defineArrayMember({ type: 'pageHeaderBand' }),
        defineArrayMember({ type: 'infoSplitCard' }),
        defineArrayMember({ type: 'labeledDisclaimers' }),
        defineArrayMember({ type: 'bulletPanelHero' }),
        defineArrayMember({ type: 'htmlEmbed' }),
      ],
      validation: (R) => R.required().min(1),
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO title',
      type: 'string',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO description',
      type: 'text',
      rows: 2,
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical URL (optional override)',
      type: 'url',
    }),
    defineField({
      name: 'noindex',
      title: 'Hide from search engines',
      type: 'boolean',
      initialValue: false,
    }),
  ],
  preview: {
    select: { title: 'title', slug: 'slug.current', sections: 'sections' },
    prepare({ title, slug, sections }) {
      const count = Array.isArray(sections) ? sections.length : 0
      return {
        title,
        subtitle: `/${slug || ''} · ${count} section${count === 1 ? '' : 's'}`,
      }
    },
  },
})
